I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/custom_selection_screen.rpy", line 23, in script
    $ strength_value_1 = mc_inicial_stats[mc][1]
  File "game/custom_selection_screen.rpy", line 23, in <module>
    $ strength_value_1 = mc_inicial_stats[mc][1]
NameError: name 'mc_inicial_stats' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/custom_selection_screen.rpy", line 23, in script
    $ strength_value_1 = mc_inicial_stats[mc][1]
  File "D:\RE\Descargas\renpy-8.3.7-sdk\renpy\ast.py", line 834, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "D:\RE\Descargas\renpy-8.3.7-sdk\renpy\python.py", line 1187, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/custom_selection_screen.rpy", line 23, in <module>
    $ strength_value_1 = mc_inicial_stats[mc][1]
NameError: name 'mc_inicial_stats' is not defined

Windows-10-10.0.19041 AMD64
Ren'Py 8.3.7.25031702
JONT Port by Rec3ks ver. 0.0.16
Fri May 16 23:34:03 2025
